version: '3'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    environment:
      - INSTANCE_IP_OR_DOMAIN=${INSTANCE_IP_OR_DOMAIN}
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
