# Generated by Django 4.2.7 on 2024-02-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cust_username",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("mech_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "booking_date",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "booking_time",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "issue_desc",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "issue_resolved_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mech_mobile",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "Bookings",
            },
        ),
        migrations.CreateModel(
            name="BookMechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issueid", models.CharField(blank=True, max_length=1000, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "vehicleType",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vehicleNo", models.CharField(blank=True, max_length=100, null=True)),
                ("issuedesc", models.CharField(blank=True, max_length=500, null=True)),
                ("phone", models.CharField(blank=True, max_length=500, null=True)),
                ("lat", models.CharField(blank=True, max_length=200, null=True)),
                ("lng", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "BookMechanic",
            },
        ),
        migrations.CreateModel(
            name="EmpLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=8)),
            ],
            options={
                "db_table": "EmpLogin",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issueid", models.CharField(blank=True, max_length=1000, null=True)),
                ("desc", models.CharField(blank=True, max_length=5000, null=True)),
                ("cust_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "cust_username",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("mech_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "mech_username",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "issue_description",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
            ],
            options={
                "db_table": "Feedback",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "no_of_bookings",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("rating", models.CharField(blank=True, max_length=200, null=True)),
                ("cust_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "cust_username",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "Profile",
            },
        ),
        migrations.CreateModel(
            name="UsersCurrentAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issueid", models.CharField(blank=True, max_length=1000, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "vehicleType",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vehicleNo", models.CharField(blank=True, max_length=100, null=True)),
                ("issuedesc", models.CharField(blank=True, max_length=500, null=True)),
                ("issuetype", models.CharField(blank=True, max_length=500, null=True)),
                ("phone", models.CharField(blank=True, max_length=500, null=True)),
                ("lat", models.CharField(blank=True, max_length=200, null=True)),
                ("lng", models.CharField(blank=True, max_length=200, null=True)),
                ("username", models.CharField(max_length=100)),
                (
                    "issue_status_id",
                    models.CharField(blank=True, max_length=69, null=True),
                ),
            ],
            options={
                "db_table": "UsersCurrentAddress",
            },
        ),
        migrations.CreateModel(
            name="UsersCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("username", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=5000)),
                (
                    "cust_email_verified",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "UsersCustomer",
            },
        ),
    ]
