# Generated by Django 4.2.7 on 2024-02-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issueid", models.CharField(blank=True, max_length=1000, null=True)),
                ("cust_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "cust_username",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("mech_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "mech_username",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "mech_assigned",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "issue_resolved_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cust_lat", models.CharField(blank=True, max_length=200, null=True)),
                ("cust_lng", models.CharField(blank=True, max_length=200, null=True)),
                ("mech_lat", models.CharField(blank=True, max_length=200, null=True)),
                ("mech_lng", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "duration_seconds",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "duration_kilometers",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "booking_time",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "booking_date",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "Booking_status",
            },
        ),
        migrations.CreateModel(
            name="MechanicDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mech_Address", models.CharField(max_length=500)),
                ("mech_city", models.CharField(max_length=50)),
                ("mech_zipcode", models.CharField(max_length=30)),
                ("mech_shop", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=100)),
                ("lat", models.CharField(blank=True, max_length=200, null=True)),
                ("lng", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "MechanicDetails",
            },
        ),
        migrations.CreateModel(
            name="Profile_mechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "no_of_bookings",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("rating", models.CharField(blank=True, max_length=200, null=True)),
                ("mech_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "mech_username",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "Profile_mechanic",
            },
        ),
        migrations.CreateModel(
            name="UsersMechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("username", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "mech_email_verified",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("password", models.CharField(max_length=5000)),
            ],
            options={
                "db_table": "UsersMechanic",
            },
        ),
    ]
