# version: '3'

# services:
#   web:
#     build: .
#     ports:
#       - "8001:8001"
#     environment:
#       - INSTANCE_IP_OR_DOMAIN=${INSTANCE_IP_OR_DOMAIN}
#     depends_on:
#       - db

#   db:
#     image: mysql:latest
#     environment:
#       MYSQL_ROOT_PASSWORD: root_password
#       MYSQL_DATABASE: mydb
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
version: '3.8'
 
services:
  mysql:
    image: mysql:latest
    networks:
      - mynetwork
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ResQify
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always
 
  django_app:
    build:
      context: .
    ports:
      - "8002:8002"
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql://admin:admin@mysql/django_testing'
    networks:
      - mynetwork
    depends_on:
      - mysql
  
networks:
  mynetwork:
    driver: bridge

